<#
  Publishes one release to Gitee: creates the release, uploads the APK as an attachment,
  and writes version.json into the repository - the file the app's "check for updates" row
  reads on a domestic network.

  Usage:
    pwsh -File tools/publish-gitee.ps1 -NotesFile artifacts/tmp/gitee-notes.md
    pwsh -File tools/publish-gitee.ps1 -Tag v1.3.5 -Name 'FN Photo 1.3.5'

  The token is a Gitee personal access token with the `projects` scope. It is read from
  -TokenFile (default artifacts/tmp/gitee-token.txt, which is git-ignored) or from
  $env:GITEE_TOKEN, and it is never echoed.

  What this writes, and why each address is the shape it is:

    - The APK goes on as a *release attachment*, not as a file in the repository: a Gitee
      repository caps a single file at 50 MB and this APK is 66 MB, while an attachment is
      capped at 100 MB. The account's total attachment allowance is 1 GB, so a repository
      holds roughly fifteen of these before older releases have to be deleted.
    - version.json goes in the *repository*, read by the app through
      https://gitee.com/<repo>/raw/<branch>/version.json. Gitee serves no `latest/download`
      alias the way GitHub does, so a file at a fixed path is the one address shape that
      needs no API call and no tag lookup at check time.
    - That raw path is cached by Gitee's CDN for 60 seconds, so a release published and
      checked within the same minute can still read the previous manifest. The script
      finishes by reading the manifest back anonymously and reporting what it found, which
      is what makes that visible rather than mysterious.

  Like the other scripts in this directory, this file is deliberately pure ASCII: Windows
  PowerShell decodes a .ps1 as ANSI unless it carries a UTF-8 BOM.
#>
[CmdletBinding()]
param(
  [string]$Repo = 'kungfucode/fn-tv-photo',
  [string]$TokenFile = '',
  [string]$Tag = '',
  [string]$Name = '',
  [string]$NotesFile = '',
  [string]$Branch = 'master',
  [string]$ProjectRoot = '',
  [switch]$NoManifest
)

$ErrorActionPreference = 'Stop'
if ([string]::IsNullOrWhiteSpace($ProjectRoot)) {
  $ProjectRoot = Split-Path -Parent $PSScriptRoot
}

$api = "https://gitee.com/api/v5/repos/$Repo"

if ([string]::IsNullOrWhiteSpace($TokenFile)) {
  $TokenFile = Join-Path $ProjectRoot 'artifacts\tmp\gitee-token.txt'
}
$token = $env:GITEE_TOKEN
if ([string]::IsNullOrWhiteSpace($token) -and (Test-Path -LiteralPath $TokenFile)) {
  $token = (Get-Content -LiteralPath $TokenFile -Raw).Trim()
}
if ([string]::IsNullOrWhiteSpace($token)) {
  throw "no Gitee token: pass -TokenFile, set GITEE_TOKEN, or write one to $TokenFile"
}

# Version and version code come from the one place they are spelled; the manifest is
# generated by release-manifest.ps1 rather than assembled here, so the two sites cannot
# describe the same build differently.
& (Join-Path $PSScriptRoot 'release-manifest.ps1') -Site 'https://gitee.com' -Repo $Repo -Tag $Tag `
  -OutFile (Join-Path $ProjectRoot 'artifacts\tmp\version-gitee.json') | Out-Host

$manifestPath = Join-Path $ProjectRoot 'artifacts\tmp\version-gitee.json'
$manifest = Get-Content -LiteralPath $manifestPath -Raw -Encoding UTF8 | ConvertFrom-Json
$apkPath = Join-Path $ProjectRoot "app\build\outputs\apk\release\$($manifest.apk)"
if (-not (Test-Path -LiteralPath $apkPath)) { throw "APK not found: $apkPath" }
if ([string]::IsNullOrWhiteSpace($Tag)) { $Tag = "v$($manifest.versionName)" }
if ([string]::IsNullOrWhiteSpace($Name)) { $Name = "FN Photo $($manifest.versionName)" }

function New-TempJson([hashtable]$Fields) {
  # PowerShell 5.1's ConvertTo-Json turns a long string into {"value": "..."} instead of
  # a plain string - and Gitee answers that with "body is invalid". Casting every string
  # through [string] first is what stops it; `$x.GetType()` says System.String either way,
  # so the cast is not redundant, it is the whole fix.
  $flat = @{}
  foreach ($key in $Fields.Keys) {
    $value = $Fields[$key]
    $flat[$key] = if ($value -is [string]) { [string]$value } else { $value }
  }
  $path = Join-Path $env:TEMP ("gitee-{0}.json" -f ([guid]::NewGuid().ToString('N')))
  $json = $flat | ConvertTo-Json -Compress
  # No BOM and UTF-8: the notes are Chinese and Gitee reads the body as UTF-8.
  [System.IO.File]::WriteAllText($path, $json, (New-Object System.Text.UTF8Encoding($false)))
  return $path
}

$auth = @('-H', "Authorization: token $token")

Write-Host "publish-gitee: $Name ($Tag) -> $Repo"

# ---------------------------------------------------------------- the release
$existing = curl.exe -sS @auth --max-time 30 "$api/releases/tags/$Tag" 2>&1 | Out-String
$rel = $null
try { $rel = $existing | ConvertFrom-Json } catch { $rel = $null }

if ($rel -and $rel.id) {
  Write-Host "  release $Tag already exists (id=$($rel.id)); uploading to it"
} else {
  # Gitee refuses a release with no body at all - "body is missing" - where GitHub is happy
  # to leave the field out, so there is always one, even when no notes were given.
  $notes = if (-not [string]::IsNullOrWhiteSpace($NotesFile) -and (Test-Path -LiteralPath $NotesFile)) {
    Get-Content -LiteralPath $NotesFile -Raw -Encoding UTF8
  } else {
    $Name
  }
  $body = @{ tag_name = $Tag; name = $Name; body = $notes; target_commitish = $Branch; prerelease = $false }
  $jsonPath = New-TempJson $body
  try {
    $created = curl.exe -sS @auth -H 'Content-Type: application/json; charset=utf-8' `
      --max-time 60 -X POST --data-binary "@$jsonPath" "$api/releases" 2>&1 | Out-String
  } finally { Remove-Item -LiteralPath $jsonPath -Force -ErrorAction SilentlyContinue }
  $rel = $created | ConvertFrom-Json
  if (-not $rel.id) { throw "could not create release $Tag : $created" }
  Write-Host "  created release id=$($rel.id)"
}

# ---------------------------------------------------------------- the APK
$size = (Get-Item -LiteralPath $apkPath).Length
Write-Host "  uploading $($manifest.apk) ($([math]::Round($size / 1MB, 1)) MiB)"
$watch = [System.Diagnostics.Stopwatch]::StartNew()
$uploaded = curl.exe -sS @auth -F "file=@$apkPath" --max-time 1800 `
  "https://gitee.com/api/v5/repos/$Repo/releases/$($rel.id)/attach_files" 2>&1 | Out-String
$watch.Stop()
$attachment = $uploaded | ConvertFrom-Json
if (-not $attachment.browser_download_url) { throw "upload failed: $uploaded" }
Write-Host ("  uploaded in {0:N1}s -> {1}" -f $watch.Elapsed.TotalSeconds, $attachment.browser_download_url)
if ($attachment.browser_download_url -ne $manifest.apkUrl) {
  Write-Warning "publish-gitee: Gitee's URL is $($attachment.browser_download_url) but the manifest says $($manifest.apkUrl)"
}

# ---------------------------------------------------------------- version.json
if (-not $NoManifest) {
  $raw = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes((Get-Content -LiteralPath $manifestPath -Raw -Encoding UTF8)))
  $current = curl.exe -sS @auth --max-time 30 "$api/contents/version.json?ref=$Branch" 2>&1 | Out-String
  $currentInfo = $null
  try { $currentInfo = $current | ConvertFrom-Json } catch { $currentInfo = $null }

  $fields = @{ content = $raw; message = "version.json for $($manifest.versionName)"; branch = $Branch }
  # Gitee differs from GitHub here: a new file is POSTed, an existing one PUT with its
  # blob sha. POSTing an update answers "文件名已存在".
  $method = 'POST'
  if ($currentInfo -and $currentInfo.sha) {
    $fields.sha = $currentInfo.sha
    $method = 'PUT'
  }
  $jsonPath = New-TempJson $fields
  try {
    $written = curl.exe -sS @auth -H 'Content-Type: application/json; charset=utf-8' `
      --max-time 60 -X $method --data-binary "@$jsonPath" "$api/contents/version.json" 2>&1 | Out-String
  } finally { Remove-Item -LiteralPath $jsonPath -Force -ErrorAction SilentlyContinue }
  $result = $written | ConvertFrom-Json
  if ($result.content) {
    $verb = if ($method -eq 'PUT') { 'updated' } else { 'created' }
    Write-Host "  version.json $verb -> sha=$($result.content.sha)"
  } else {
    Write-Warning "publish-gitee: version.json not written: $written"
  }
}

# ---------------------------------------------------------------- read it back
# Anonymously, with no token and no browser user agent, because that is exactly how the
# app asks. Gitee caches this path for a minute, so a stale read here is the cache and not
# a failure - it is reported rather than hidden precisely so that it is not mistaken for one.
$rawUrl = "https://gitee.com/$Repo/raw/$Branch/version.json"
Write-Host "  reading back $rawUrl"
$readBack = curl.exe -sS -A 'FN-Photo-TV' -L --max-time 60 $rawUrl 2>&1 | Out-String
try {
  $live = $readBack | ConvertFrom-Json
  if ($live.versionName -eq $manifest.versionName -and $live.sha256 -eq $manifest.sha256) {
    Write-Host "  live manifest matches: $($live.versionName) ($($live.versionCode))"
  } else {
    Write-Warning "publish-gitee: live manifest says $($live.versionName)/$($live.sha256), expected $($manifest.versionName)/$($manifest.sha256) - Gitee's 60s cache, most likely"
  }
} catch {
  Write-Warning "publish-gitee: could not read the manifest back: $readBack"
}
